# Generated by Django 4.2.3 on 2023-08-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medremainder',
            name='remind_number_days',
            field=models.DateField(),
        ),
    ]
